### PR TITLE
Test mac os

### PR DESCRIPTION
**Pull request by meo-pill**
the macOS test sequence fail a the first one so i think that a problème

### CODE REVIEW

**Comment by meo-pill** [comment]
for the shellcheck fail do i add a ignore or do i remove the yellow color ?

**Comment by markusressel** [comment]
Hey @meo-pill, thx for the PR!

You can remove the Yellow color for now, if we ever need it we can always add it back.

Looks like the macOS build doesn't work yet, any idea why?

**Comment by markusressel** [comment]
Looks good! Is this PR ready for merging?

**Comment by meo-pill** [comment]
Yes for me it ok to merge.

Mayby add a freeBSD test on github action but that can be done on anothoer PR
(freeBSD in not natively supporter on github action so it need to go trhou a vm see : https://github.com/marketplace/actions/freebsd-vm)

**Comment by markusressel** [comment]
Great!
Yes FreeBSD would be nice, and the testing script isn't complete by any means either.
But this PR is a step in the right direction :+1:

**Pull request merged**
