### PR TITLE
remove bc dependency since TrueNAS Scale doesn't include it.

### PR DESCRIPTION
**Pull request by StraightfaceStudios**

### CODE REVIEW

**Comment by markusressel** [comment]
Hey @StraightfaceStudios !
Thx for opening a PR 🤓 

Is the script outputting the exact same text to the console after this change? Can you please post examples of old and new to compare?

**Comment by SCNickF1227** [comment]
`progress_percent=$((current_index * 100 / file_count))`
In line 72 fixes this problem. Let me know if you want a new PR.

`
Progress -- Files: 7/130564 (0%)
Copying '/mnt/excitement/FileName.me' to '/mnt/excitement/FileName.me.balance'...

`

**Comment by markusressel** [comment]
> Not sure why this wasn't merged, but it's still open.

Because the tests are failing.
Looks like the decimals are gone and shellcheck isn't happy.

**Comment by markusressel** [comment]
Closing this in favor of #24

**Pull request closed without merging**
